### ISSUE TITLE
Export as prompt or Github issue

### ISSUE THREAD

**Issue by sunmer** [sunmer/checkra#33]
Here’s a turnkey “engineering prompt” you can hand to another LLM (or human) who has full write-access to the repo.  
It states the desired UX, the relevant files, and concrete acceptance criteria.

---

## Feature request  
Add a contextual **action-menu** to every applied-fix bubble in the viewer.  
The menu lives to the immediate right of the existing “show ↔ hide” toggle (`feedback-fix-toggle`) and exposes two actions:

1. **“Copy as prompt”** – copies a plain-text prompt that describes this HTML change (original ⇒ modified) to the clipboard so the user can paste it into Cursor, ChatGPT, etc.  
2. **“Export to GitHub as ticket”** – opens a new-issue URL in the project’s GitHub repo with the same prompt pre-filled into the body (and a short title).

### Visual
```
[ toggle-eye-icon ] [ ⋮ ]  <- click
                 └─ dropdown:
                      • Copy as prompt        ⌘C
                      • Export to GitHub
```

---

## Relevant code hotspots

1. `src/ui/feedback-viewer-impl.ts`  
   • Function `createAppliedFixButton()` currently makes the close (`×`) and toggle buttons.  
   • The applied-fix wrapper div is created a few lines above that.

2. `src/ui/feedback-viewer-dom.ts`  
   • Manages DOM updates and CSS classes for the viewer.

3. `src/ui/feedback-viewer.css` (not shown here) – where you’ll add minimal styles for the new menu / dropdown.

---

### A. Prompt text
For a given `fixId` you already store:

```ts
interface AppliedFixInfo {
  originalHtml: string
  appliedHtml: string
  targetSelector: string
  // ...
}
```

Build the prompt as:

```
Rewrite the DOM element selected by: <targetSelector>
FROM:
<originalHtml>
TO:
<appliedHtml>
```

(Guard against backticks or triple-backticks so Markdown isn’t broken inside GitHub.)

### B. UI
1. Create a new button inside `createAppliedFixButton()` when `type === 'menu'` – give it id/class `feedback-fix-menu`.  
2. Use a simple `<div class="dropdown">` that toggles `hidden` class on click; no external libs needed.  
3. Keyboard shortcut: when dropdown is open, hitting `c` triggers “copy as prompt”.

### C. Clipboard / GitHub
```ts
await navigator.clipboard.writeText(promptText);
window.open(
  `https://github.com/<owner>/<repo>/issues/new?title=${encodeURIComponent("UI change suggestion")}&body=${encodeURIComponent(promptText)}`,
  "_blank"
);
```
Replace `<owner>/<repo>` with the real repo or read it from `package.json`.

### D. State management
No new global state is required; you can reuse `fixInfoMap` keyed by `fixId`.

### E. CSS (tiny)
```css
.feedback-fix-menu { background: transparent; border:none; cursor:pointer; }
.feedback-fix-dropdown { position:absolute; right:0; top:100%; background:#fff; border:1px solid #ccc; border-radius:4px; display:none; z-index:1000; }
.feedback-fix-dropdown.visible { display:block; }
.feedback-fix-dropdown button { display:block; width:100%; padding:6px 12px; text-align:left; }
```

---

## Acceptance criteria

1. A vertical-ellipsis button appears next to every applied-fix toggle; it is hidden when the fix bubble is collapsed (unchanged behaviour).  
2. Clicking the button reveals a dropdown with the two actions.  
3. “Copy as prompt” places the prompt in the clipboard and shows a temporary tooltip (“Copied!”).  
4. “Export to GitHub” opens a new tab pointing at the repo’s issue-creation page with title/body prefilled.  
5. No linter errors, unit tests pass (`npm run test`), bundle still builds (`npm run build`), and filesize increase < 2 KB gzipped.

---

Feel free to share this prompt directly with the next LLM/human engineer.
